language: python
python:
- '2.7'
- '3.5'
- '3.6'
services: mongodb
install:
- pip install coveralls
- pip install flake8
- pip install -r requirements.txt
before_script:
- sleep 15
- flake8 .
script:
- nosetests --with-coverage --cover-package=vulnpryer
after_success:
- coveralls
before_deploy:
- export RELEASE_PKG_FILE=$(ls dist/VulnPryer-*.zip)
- echo "Deploy target for GitHub is $RELEASE_PKG_FILE"
deploy:
- provider: releases
  api_key:
    secure: K8TS3uWwydoqrQ+lQdZbCJ1A9V9BVAZKOn8G1P77cEhZOTLT4a4gPZp+vmQQF2YmJDJUyrd4gqQD8mnvY3aCdqldHHDS9CCCuUgSl7hSK4zDsD6VSuR3zCp6UDuUAWAxzQwmc2Xpeh+xqZfI4CD4IvUQ/bYwDTedRxRwziD90Mw=
  file_glob: true
  file: dist/VulnPryer-*.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
- provider: pypi
  server: https://testpypi.python.org/pypi
  user: davidski
  skip_cleanup: true
  distributions: sdist bdist_wheel
  password:
    secure: UrMA+gNEn4qSKaEYk2r8/b3TDneRC5Tm2xHKVjUBRI3z5E+wECp3nccPC9KPgnDH0gn5qr5UIw9xaehRjod2KecC3qWAm2tzUnNaJYHppISv05cQVU681qbDtJpIsS+ECJJ57MuPcLNJkJYM4ZN+n1XbvQpCH6Bn0jrPoe7A/I0=
  on:
    tags: true
    branch: dev
- provider: pypi
  server: https://pypi.python.org/pypi
  user: davidski
  skip_cleanup: true
  distributions: sdist bdist_wheel
  password:
    secure: pmA/v6ECxgZLM6vMfwGEZen+NeMXCINm/oDf2iTLszjJKZ6hp0ov13JxAOju5b4X1h+lTeYht+q++9qZo87dGwgnbJhQJztddLb1YsJCw+Ryk1FKdqiB9iQp/YF/HNtFjFgcCIEJ/S777QY57VyftoPBTC9biL5Q18udt/MUQWhjW4Y2PvVD7ykmSKzFUr0pJgA8wdaiSC13o/JQqKXDrEVVtKtDicVyvOVaHj6wfMnShVfbbhhGFIqvbVBHTGUsnXbq4ePviiftpblhVH5WzYbsn9v3e6vDAOvypsd/eD8DQqQ+B79rw0sY47Vziz9C3AwRRP+wliZdcZgLa5LrkBhamSraE5NhJIzd4Xzftul0PfQm/FSIaQ5DgUTOqFcec2wxcfB/04GMw+6Ixgf7dSfTmsmD/Qm7f5DcWVxBQzQA+Ybak/Anor+jY2CtB1PrTxlXGs2yq8AoE/GDn8wX3ztWAt60mGY6fN85spc7fiIz+1+gzYCofxcRIncBdOqgx38ulVWXgcZLtlq09MXZrZ1RWhhcLh912XBTyYhxF66EZ+VYm4FSbXtQ3knhR8JnD94ewW7Da7VRzEDxC+TsYXtW6/rlvlFkJ7PU0NcI2cd9jsqrHv3aK3AGp6lHSG6vtOZyQ+V+vELtOfKtj5fJgT3jmEOTw71h7lJb3Ha0P0I=
  on:
    tags: true
    branch: master
notifications:
  slack:
    secure: JInQysMjcB6VzBWAo7dqxLtXnyimsjGLN060H7ewfMBwYkyr2WOfPATPEjNxPZXJ38lkjKfPoViLLxWFiJOySue0FuY75Nb1Fn8AUcJkou7itwaW9nSRqNOTdc0eTZZYlxSQwaV2bRTCxObFJHPSVMh2zLmvLryJSwJCvTFK1Zs=
