language: python

python:
  - '2.7'
  - '3.5'

services: mongodb

install:
  - pip install --user flake8
  - pip install --user -r requirements.txt

before_script:
  - sleep 15
  - flake8 .

script: nosetests

before_deploy:
  - python $TRAVIS_BUILD_DIR/ci/travis_set_build.py --file-paths '("vulnpryer", "__init__.py")' --skip "$TRAVIS_TAG"

deploy:
  - provider: releases
    api_key: ""
    file: "vulnpryer.zip"
    skip_cleanup: true
    on:
      tags: true

  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: davidski
    password:
      secure: "U7h6bE6IQZjBO+aaNQejvugyxFlEv5UeoHx5BAtS5FWgm6+qq0XU/98OyCuApzIxkuViwh8+BIrlZ8jB6+f8tEA6+yklJqVQUxYcxs7vOnyTtCWWBnOZUrsSdAuLBDCrx4JeWEbtq3451yQsr56Cm1ZOxU4wDvInxXvjV0EWWMUD0A4GeWR2FBujCX1ROFWTiw1dIC8xZ+bZGI8DHr7TLHkJXXpCg6xOmf+ArI1h3DWw3W3D+dUVQqaoLzV/WrjxAWHeWcRcotYqF7Uqu5KASWYrKYVe7RCx869WBWbYb0Wmhf1clT+JMDbsrY4sZ3w8YjD4eyH74jeHH+dkL7M/fI1IKyUOABLAgEdGBzl6ZkcxjFBMUcM8/aGcwBgLhm0bKKmFVAqm5OAjNLFkbFMDIQ1ox72iKtXqDCLeDNVsF5iwKmWw6+8Euj89+yOs5U/n/Cmc3YumCuO1FuFV0r05IPTpNkN2mn5oGjjKSEZJ1SVovzcg98Ce3ABfAsVX6y6KnCz1IJ8hN4nEjkL08wbmNenD3ExejQcAaKWyrOUkObwxp/4fPZKookMH2kn4T0arfd+HtwTPMnouUxzKt/FkCRa0Md3FkvcNgWszSvfiIiIngAICUPRvCXDxkG9utskmSE25uyEDD7UN7D57SX8x2fLsyugNzrlpZbZpPGRome8="
    on:
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
      
  - provider: pypi
    user: davidski
    password:
      secure: "U7h6bE6IQZjBO+aaNQejvugyxFlEv5UeoHx5BAtS5FWgm6+qq0XU/98OyCuApzIxkuViwh8+BIrlZ8jB6+f8tEA6+yklJqVQUxYcxs7vOnyTtCWWBnOZUrsSdAuLBDCrx4JeWEbtq3451yQsr56Cm1ZOxU4wDvInxXvjV0EWWMUD0A4GeWR2FBujCX1ROFWTiw1dIC8xZ+bZGI8DHr7TLHkJXXpCg6xOmf+ArI1h3DWw3W3D+dUVQqaoLzV/WrjxAWHeWcRcotYqF7Uqu5KASWYrKYVe7RCx869WBWbYb0Wmhf1clT+JMDbsrY4sZ3w8YjD4eyH74jeHH+dkL7M/fI1IKyUOABLAgEdGBzl6ZkcxjFBMUcM8/aGcwBgLhm0bKKmFVAqm5OAjNLFkbFMDIQ1ox72iKtXqDCLeDNVsF5iwKmWw6+8Euj89+yOs5U/n/Cmc3YumCuO1FuFV0r05IPTpNkN2mn5oGjjKSEZJ1SVovzcg98Ce3ABfAsVX6y6KnCz1IJ8hN4nEjkL08wbmNenD3ExejQcAaKWyrOUkObwxp/4fPZKookMH2kn4T0arfd+HtwTPMnouUxzKt/FkCRa0Md3FkvcNgWszSvfiIiIngAICUPRvCXDxkG9utskmSE25uyEDD7UN7D57SX8x2fLsyugNzrlpZbZpPGRome8="
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.5"
