language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

services: mongodb

install:
  - pip install flake8
  - pip install -r requirements.txt

before_script:
  - sleep 15
  - flake8 .

script: nosetests

deploy:
  - provider: releases
    api_key:
      secure: "HfpgzwjL6bVXwrE0Zqex0BxdQlyQ6KysWTE9XBRkiWZwXZ9lv1kfoq4lwrWu13xLKQX2gyKYwKnyrFtqgq5RM/jgypAdxbPdzGeScwCuO0do1dyku+cQcXxF2xHz6Z3N6OvZseSBjCMA5i31VsL6u/K/608enH+ex7PSAd8kqnNuMfkdej1er8FjmKNIvDTSQ5xpaurFUV2k585AA+pgLAiS/LERyvb33a+hj9z2q+wohZx6QjB1ph4moif40rwlCdOddaSv3gXHmOcu3M+GMRgktl8+qFhUpN9QJrADTLMGVkewfDkXX850bWYPaKPmkghnP3fxEW6/hpT1BIjAHZ1vGDMS8yXmR6dTfxfrYuVKww6ScVen1x4DLGEtykQIPtszxiv4/VtOEEtm2HN5AsRATpjq9MTkpJovjP5cWp0AI8ujyyxg+GLFJnrw/DPdDSnyInO87zvkmP48ATQD4UmYS/OCKoA4ONgau4bw2PsAVgIXT4bU3fe2r6WsPMiwsCgSpTIfeodwLOxZhyO1o2hLonWtGr58GDA2KVqxlXObjGP7TnqUkW145Wj1bU08vHxqBgiIxWrTqACLcVZSRVXhlSUqZvZYd8W8TWek7XUlf6sTymKQceYevnoSQaGUA/U3MpWzJ8Sw3czMOq+ZCvoJ4xLQZVL9DlLF7arvRDM="
    file: "vulnpryer.zip"
    skip_cleanup: true
    on:
      tags: true

  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: davidski
    skip_cleanup: true
    password:
      secure: "U7h6bE6IQZjBO+aaNQejvugyxFlEv5UeoHx5BAtS5FWgm6+qq0XU/98OyCuApzIxkuViwh8+BIrlZ8jB6+f8tEA6+yklJqVQUxYcxs7vOnyTtCWWBnOZUrsSdAuLBDCrx4JeWEbtq3451yQsr56Cm1ZOxU4wDvInxXvjV0EWWMUD0A4GeWR2FBujCX1ROFWTiw1dIC8xZ+bZGI8DHr7TLHkJXXpCg6xOmf+ArI1h3DWw3W3D+dUVQqaoLzV/WrjxAWHeWcRcotYqF7Uqu5KASWYrKYVe7RCx869WBWbYb0Wmhf1clT+JMDbsrY4sZ3w8YjD4eyH74jeHH+dkL7M/fI1IKyUOABLAgEdGBzl6ZkcxjFBMUcM8/aGcwBgLhm0bKKmFVAqm5OAjNLFkbFMDIQ1ox72iKtXqDCLeDNVsF5iwKmWw6+8Euj89+yOs5U/n/Cmc3YumCuO1FuFV0r05IPTpNkN2mn5oGjjKSEZJ1SVovzcg98Ce3ABfAsVX6y6KnCz1IJ8hN4nEjkL08wbmNenD3ExejQcAaKWyrOUkObwxp/4fPZKookMH2kn4T0arfd+HtwTPMnouUxzKt/FkCRa0Md3FkvcNgWszSvfiIiIngAICUPRvCXDxkG9utskmSE25uyEDD7UN7D57SX8x2fLsyugNzrlpZbZpPGRome8="
    on:
      tags: false
      branch: dev
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
      
  - provider: pypi
    user: davidski
    skip_cleanup: true
    password:
      secure: "pmA/v6ECxgZLM6vMfwGEZen+NeMXCINm/oDf2iTLszjJKZ6hp0ov13JxAOju5b4X1h+lTeYht+q++9qZo87dGwgnbJhQJztddLb1YsJCw+Ryk1FKdqiB9iQp/YF/HNtFjFgcCIEJ/S777QY57VyftoPBTC9biL5Q18udt/MUQWhjW4Y2PvVD7ykmSKzFUr0pJgA8wdaiSC13o/JQqKXDrEVVtKtDicVyvOVaHj6wfMnShVfbbhhGFIqvbVBHTGUsnXbq4ePviiftpblhVH5WzYbsn9v3e6vDAOvypsd/eD8DQqQ+B79rw0sY47Vziz9C3AwRRP+wliZdcZgLa5LrkBhamSraE5NhJIzd4Xzftul0PfQm/FSIaQ5DgUTOqFcec2wxcfB/04GMw+6Ixgf7dSfTmsmD/Qm7f5DcWVxBQzQA+Ybak/Anor+jY2CtB1PrTxlXGs2yq8AoE/GDn8wX3ztWAt60mGY6fN85spc7fiIz+1+gzYCofxcRIncBdOqgx38ulVWXgcZLtlq09MXZrZ1RWhhcLh912XBTyYhxF66EZ+VYm4FSbXtQ3knhR8JnD94ewW7Da7VRzEDxC+TsYXtW6/rlvlFkJ7PU0NcI2cd9jsqrHv3aK3AGp6lHSG6vtOZyQ+V+vELtOfKtj5fJgT3jmEOTw71h7lJb3Ha0P0I="
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.6"
