language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  #- pip install .
  - "pip install flake8 --use-mirrors"
  - "pip install -r requirements.txt"
before_script:
  - flake8 .
# command to run tests
script: nosetests